

zuul:
  #prefix: /api

  #Ignores specified services
  #ignored-services: app-two

  #Ignores all services -> ids have to be explicitly configured
  #ignored-services: *

  routes:
     app-one:
      path: /app-one
      serviceId: app-one

     app-two:
       path: /second-application
       serviceId: app-two